2024-10-12 11:05:54,156 - root - INFO - READING DATA_GRID FILE...
2024-10-12 11:05:54,156 - root - INFO - Successfully loaded data_grid file: ops/10121105-1000SATS-S.json
2024-10-12 11:05:54,158 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): api.binance.com:443
2024-10-12 11:05:54,517 - urllib3.connectionpool - DEBUG - https://api.binance.com:443 "GET /api/v3/ping HTTP/11" 200 2
2024-10-12 11:05:54,517 - root - INFO - POSTING ENTRY ORDER TO BINANCE...
2024-10-12 11:05:54,519 - urllib3.connectionpool - DEBUG - Starting new HTTPS connection (1): fapi.binance.com:443
2024-10-12 11:05:55,662 - urllib3.connectionpool - DEBUG - https://fapi.binance.com:443 "POST /fapi/v1/order?newClientOrderId=IN_10121105-1000SATS-S_4b18a&positionSide=SHORT&price=0.0002846&quantity=0&side=SELL&symbol=1000SATSUSDT&timeInForce=GTC&timestamp=1728745554518&type=LIMIT&signature=538d13dcdded440afbf4b8d7a53b8ecd0069f0a68d57f5308ef07231edac32de HTTP/11" 400 59
2024-10-12 11:05:55,662 - root - ERROR - Error placing entry_line order: {'entry': 'IN', 'side': 'SELL', 'position_side': 'SHORT', 'price': 0.0002846, 'quantity': 0, 'cost': 0.0, 'order_id': 0, 'status': 'NEW', 'client_order_id': ''} 
 APIError(code=-4003): Quantity less than or equal to zero.
Traceback (most recent call last):
  File "/Users/eddysan/Documents/LUBinance_dev/packages.py", line 342, in post_entry_order
    response = self.client.futures_create_order(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/binance/client.py", line 6504, in futures_create_order
    return self._request_futures_api('post', 'order', True, data=params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/binance/client.py", line 383, in _request_futures_api
    return self._request(method, uri, signed, True, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/binance/client.py", line 359, in _request
    return self._handle_response(self.response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/lib/python3.12/site-packages/binance/client.py", line 368, in _handle_response
    raise BinanceAPIException(response, response.status_code, response.text)
binance.exceptions.BinanceAPIException: APIError(code=-4003): Quantity less than or equal to zero.
2024-10-12 11:05:55,672 - root - INFO - GENERATING DATA_GRID...
